version: "2"
services: 
  stable-diffusion-webui-rocm:
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      # VERY COMMON NEED ENVIRONMENT VARIABLE
      # Match detected GPU gfx1201 (RX 9070)
      - HSA_OVERRIDE_GFX_VERSION=12.0.1
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      # Following line is needed to RX 5700
      # - COMMANDLINE_ARGS='--precision full --no-half'
      - COMMANDLINE_ARGS=--skip-torch-cuda-test --precision full --no-half
    group_add:
      # Host Video Group Id
      - 984
      # Host Render Group Id
      - 988
    image: stable-diffusion-webui-rocm:6.4
    ipc: host
    network_mode: "host"
    shm_size: "8G"
    security_opt:
      - seccomp:unconfined
    volumes:
      - configs:/sd/configs
      - models:/sd/models
      - plugins:/sd/plugins
      - outputs:/sd/outputs
      - extensions:/sd/extensions
volumes:
  configs:
  models:
  plugins:
  outputs: 
  extensions:
